[package]
name = "podium-demux"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
podium-core = { path = "../core" }
log.workspace = true
symphonia.workspace = true
